reintroduce set_parameters for audio hal without create_audio_patch
mer-hybris/pulseaudio-modules-droid pull request #117
Opened 2022-10-17 07:58 UTC by Kethen

It is possible for android 11 audio hal to not implement create_audio_patch, when that happens, the create_audio_patch function pointer could be null or garbage value depending on implementation as discussed over https://github.com/ubports/pulseaudio-modules-droid-30/pull/1, causing segfaults during create_audio_patch usage 

It is possible to not support createAudioPatch:
https://cs.android.com/android/platform/superproject/+/android-11.0.0_r48:frameworks/av/media/libaudiohal/include/media/audiohal/DeviceHalInterface.h;drc=9b2064c3afe14f893afff019bdcd4c4d40ce13ed;l=93

Android 11 Audio hal implemented without create_audio_patch:
https://cs.android.com/android/platform/superproject/+/android-11.0.0_r48:hardware/qcom/audio/hal/audio_hw.c

2023-06-07 08:37 UTC, jusa requested changes
Can you change the commit message to

```
common: Reintroduce set_parameters for audio hal without create_audio_patch

It is possible for android 11 audio hal to not implement create_audio_patch,
when that happens, the create_audio_patch function pointer could be null or
garbage value depending on implementation as discussed over
ubports/pulseaudio-modules-droid-30#1, causing segfaults during
create_audio_patch usage

It is possible to not support createAudioPatch:
https://cs.android.com/android/platform/superproject/+/android-11.0.0_r48:frameworks/av/media/libaudiohal/include/media/audiohal/DeviceHalInterface.h;drc=9b2064c3afe14f893afff019bdcd4c4d40ce13ed;l=93

Android 11 Audio hal implemented without create_audio_patch:
https://cs.android.com/android/platform/superproject/+/android-11.0.0_r48:hardware/qcom/audio/hal/audio_hw.c

[common] Reintroduce set_parameters for audio hal without create_audio_patch. Fixes JB#60851
```

2023-06-07 08:37 UTC, jusa commented on src/common/droid-util.c
> +
nit: Quite a lot of double new lines

2023-06-13 06:54 UTC, Kethen commented
The requested changes has been added

2026-05-12 07:19 UTC, jusa commented
Apologies, this was forgotten for a bit. Merging now.

2026-05-12 07:24 UTC, jusa approved these changes

2026-05-12 07:24 UTC, merged