conversion: allow parsing sampling rates with spaces
mer-hybris/pulseaudio-modules-droid pull request #124
Opened 2023-07-27 17:26 UTC by muhammad23012009

* allows parsing version 7 of audio policy configuration

2023-07-28 10:49 UTC, muhammad23012009 commented
Before:
```
Jul 23 15:22:42 ubuntu-phablet pulseaudio[2760]: [/vendor/etc/bluetooth_audio_policy_configuration.xml:9] Bad sample rate value 24000 16000
Jul 23 15:22:42 ubuntu-phablet pulseaudio[2760]: [/vendor/etc/bluetooth_audio_policy_configuration.xml:9] Failed to parse element <profile>
Jul 23 15:22:42 ubuntu-phablet pulseaudio[2760]: parsing aborted at line 11
Jul 23 15:22:42 ubuntu-phablet pulseaudio[2760]: Assertion '!data.current_module' failed at ../../src/common/config-parser-xml.c:1230, function pa_parse_droid_audio_config_xml(). Aborting.
```
pa-droid would fail to read sample rates with spaces between.
XML file:
```
<?xml version="1.0" encoding="UTF-8"?>
<!-- Bluetooth Audio HAL Audio Policy Configuration file -->
<module name="bluetooth" halVersion="2.0">
    <mixPorts>
        <!-- A2DP Audio Ports -->
        <mixPort name="a2dp output" role="source"/>
        <!-- Hearing AIDs Audio Ports -->
        <mixPort name="hearing aid output" role="source">
            <profile name="" format="AUDIO_FORMAT_PCM_16_BIT"
                     samplingRates="24000 16000"
                     channelMasks="AUDIO_CHANNEL_OUT_STEREO"/>
        </mixPort>
    </mixPorts>
    ...
```
Now works reliably, still need to find more things to fix for policy version 7

2023-08-29 15:00 UTC, jusa requested changes

2023-11-30 11:13 UTC, muhammad23012009 commented on src/common/conversion.c
> +    while ((entry = pa_split(str, separator, &state))) {
Been a while, but I finally got round to this, and fixed.

2024-03-21 14:42 UTC, mlehtima approved these changes

2024-03-21 14:43 UTC, merged